/*
 * This source file was generated by the Gradle 'init' task
 */
package estructuras;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ListaEnlazadaTest {

    @Test
    void testEliminarParesConListaVacia() {
        ListaEnlazada.Nodo cabeza = null;
        ListaEnlazada.Nodo resultado = ListaEnlazada.eliminarPares(cabeza);
        assertNull(resultado, "La lista debería ser nula");
    }

    @Test
    void testEliminarParesSinNodosPares() {
        ListaEnlazada.Nodo cabeza = new ListaEnlazada.Nodo(1);
        cabeza.siguiente = new ListaEnlazada.Nodo(3);
        cabeza.siguiente.siguiente = new ListaEnlazada.Nodo(5);

        ListaEnlazada.Nodo resultado = ListaEnlazada.eliminarPares(cabeza);
        assertNotNull(resultado, "La lista no debería ser nula");
        assertEquals(1, resultado.dato);
        assertEquals(3, resultado.siguiente.dato);
        assertEquals(5, resultado.siguiente.siguiente.dato);
        assertNull(resultado.siguiente.siguiente.siguiente);
    }

    @Test
    void testEliminarParesConNodosPares() {
        ListaEnlazada.Nodo cabeza = new ListaEnlazada.Nodo(2);
        cabeza.siguiente = new ListaEnlazada.Nodo(4);
        cabeza.siguiente.siguiente = new ListaEnlazada.Nodo(6);

        ListaEnlazada.Nodo resultado = ListaEnlazada.eliminarPares(cabeza);
        assertNull(resultado, "La lista debería ser nula");
    }

    @Test
    void testEliminarParesConNodosMixtos() {
        ListaEnlazada.Nodo cabeza = new ListaEnlazada.Nodo(1);
        cabeza.siguiente = new ListaEnlazada.Nodo(2);
        cabeza.siguiente.siguiente = new ListaEnlazada.Nodo(3);
        cabeza.siguiente.siguiente.siguiente = new ListaEnlazada.Nodo(4);
        cabeza.siguiente.siguiente.siguiente.siguiente = new ListaEnlazada.Nodo(5);

        ListaEnlazada.Nodo resultado = ListaEnlazada.eliminarPares(cabeza);
        assertNotNull(resultado, "La lista no debería ser nula");
        assertEquals(1, resultado.dato);
        assertEquals(3, resultado.siguiente.dato);
        assertEquals(5, resultado.siguiente.siguiente.dato);
        assertNull(resultado.siguiente.siguiente.siguiente);
    }
}
